port: 4300

default-url: https://www.google.com

resources:

  googleR:
    name: googleR
    matchers: /**
    type: reverse-proxy
    url: https://www.google.com

  google:
    name: google
    matchers: /search
    type: reverse-proxy
    url: https://www.google.com

  test:
    name: test
    matchers: /resource1/resource2
    type: reverse-proxy
    #url: https://www.google.com
